### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type mustache::Exception: Unknown type0

### ISSUE THREAD

**Issue by Stubbs** [jbboehr/libmustache#8]
I'm trying to write a test for the Homebrew installer, (see Homebrew/homebrew#40626) and they've asked if I can write a better test than `mustache -h` :-)

I've created a very simple template & data file, but when I try and compile the template I get the error below:

    libc++abi.dylib: terminating with uncaught exception of type mustache::Exception: Unknown type0

Here's the simple files I'm using:

Data:
```yml
---
colours: [{name: 'Red'}, {name: 'Green'}, {name: 'Blue'}]
```

Template:
```mustache
{{#colours}}{{name}}{{/colours}}
```

and when  try and run various commands over them I get get the error.

```bash
~  mustache -c -t names.tache -d names.yml
libc++abi.dylib: terminating with uncaught exception of type mustache::Exception: Unknown type0
[1]    60831 abort      mustache -c -t names.tache -d names.yml

~  mustache -p -t names.tache -d names.yml
[1]    60913 segmentation fault  mustache -p -t names.tache -d names.yml
```

and using -e doesn't give any output, If I use -o to output to a file, the file is empty.

**Comment by jbboehr** [comment]
It looks like there was some missing code in the data conversion routines. It's not necessary for the php extension (I had mainly used it for debugging originally), so it looks like the test suites didn't catch it.

**Comment by jbboehr** [comment]
Unfortunately, the mustache spec files are not in the release tarball because it's in a git submodule, but I think running `make test` would be the best mode of verifying correct operation.

**Comment by Stubbs** [comment]
Do you mean the mustache binary was mainly used for testing?

**Comment by jbboehr** [comment]
Development, but, of course, it's supposed to work as well.

**Comment by jbboehr** [comment]
It should be working now: https://github.com/jbboehr/libmustache/tree/v0.3.2

**Comment by jbboehr** [comment]
By binary, I mean bin/mustache, not the library.

**Comment by Stubbs** [comment]
I'm still getting segfaults trying to compile that simple template. What template/data do you use to test it with?

If you have a look at the brew recipe for tinyxml2 they test it by writing a small bit of C++ & compiling it:

```
    (testpath/"test.cpp").write <<-EOS.undent
      #include <tinyxml2.h>
      int main() {
        tinyxml2::XMLDocument doc (false);
        return 0;
      }
    EOS
    system ENV.cc, "test.cpp", "-L#{lib}", "-ltinyxml2", "-o", "test"
    system "./test"
```

Is there a tiny bit of code I can compile like that to test it?

**Comment by jbboehr** [comment]
I tried the template you used above. I'll see if I can take a look with one of the Macs at the office; my computer runs Ubuntu.

If you can send me a valgrind of the segfault, that would help me troubleshoot. Note that the bin/mustache file in the project folder is usually a shell script (at least on ubuntu), so valgrind won't work on it directly.

The above seems to just test if the library can be linked after being installed. Some code like this should accomplish that:

```cpp
#include <mustache/mustache_config.h>
#include <mustache/mustache.hpp>
int main() {
        mustache::Mustache m;
        mustache_version_int();
        return 0;
}
```

```sh
$ g++ -std=c++11 -c -o test.o test.cpp
$ g++ -std=c++11 -o test test.o -lmustache
$ ./test && echo "Ok"
Ok
$ readelf -d test | head -7

Dynamic section at offset 0x2df8 contains 27 entries:
 0x0000000000000001 (NEEDED)             ..... [libmustache.so.3]
 0x0000000000000001 (NEEDED)             ..... [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             ..... [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             ..... [libc.so.6]
````

**Comment by Stubbs** [comment]
I went for the simple that that checks if libmustache can be linked. Thanks John. This now builds & passes on Homebrew's test platform so hopefully it'll be merged soon & I can see about the PHP modules next.

**Comment by jbboehr** [comment]
Great!

**Comment by Stubbs** [comment]
Libmustache & the PHP Mustache extension are now available for php5.5 -> 5.7 via "brew" on OSX :-)

**Comment by jbboehr** [comment]
Great, thanks! What's the process to install it? I can add it to the readme, or you can send a PR if you want.
